KeyValueStorage: benchmark.cpp File Reference
benchmark.cpp File Reference
#include <iostream>
#include <random>
#include <chrono>
#include <storage/BloomFilter.hpp>
#include <serializer/RecordSerializer.hpp>
#include <serializer/TrieNodeSerializer.hpp>
#include <storage/File.hpp>
#include <storage/Log.hpp>
#include <storage/Storage.hpp>
#include <storage/Trie.hpp>
#include <KeyValueStore.hpp>
Functions
std::mt19937 random_data (2)
int main ()
Function Documentation
main()
int main ()
References kvs::KeyValueStore::add(), kvs::KeyValueStore::get(), kvs::Id::getIdSize(), and random_data().
random_data()
std::mt19937 random_data (2)
Referenced by main().