KeyValueStorage: kvs::KeyValueStore Class Reference
kvs::KeyValueStore Class Reference
Главный класс, хранилище пар < Key, Value >
#include <KeyValueStore.hpp>
Public Member Functions
KeyValueStore (BloomFilter &bloomFilter, Log &log, Trie &trie, Storage< Record > &_recordStorage)
void add (const KeyValue &keyValue)
std::optional< KeyValue > get (const Key &key) const
void del (const Key &key)
void clear ()
Detailed Description
Главный класс, хранилище пар < Key, Value >
Constructor & Destructor Documentation
KeyValueStore()
kvs::KeyValueStore::KeyValueStore (BloomFilter & bloomFilter, Log & log, Trie & trie, Storage< Record > & _recordStorage)
Parameters
bloomFilter Фильтр Блума.
log Лог в качестве хранилища в оперативной памяти.
trie Бор в качестве хранилища на диске.
_recordStorage Хранилище записей Record на диске.
Member Function Documentation
add()
void kvs::KeyValueStore::add (const KeyValue & keyValue)
Добавить keyValue в хранилище.
Parameters
keyValue пара Key, Value.
References kvs::BloomFilter::add(), kvs::Log::add(), kvs::Storage< Record >::add(), kvs::Log::clear(), kvs::Log::LogIterator::end(), kvs::KeyValue::getKey(), kvs::KeyValue::getValue(), kvs::Log::isFull(), kvs::Storage< Record >::isFull(), kvs::Trie::merge(), kvs::Storage< Record >::remove(), kvs::Storage< Record >::removeRecordsById(), and kvs::Log::toInMemoryTrieNode().
Referenced by main().
clear()
void kvs::KeyValueStore::clear ()
Очистить KeyValueStore.
References kvs::Storage< Record >::clear(), kvs::Log::clear(), kvs::Trie::clear(), and kvs::Storage< Record >::size().
del()
void kvs::KeyValueStore::del (const Key & key)
Удалить пару Key, Value по ключу key.
Parameters
key Ключ.
References kvs::Storage< Record >::isFull(), kvs::BloomFilter::mightContains(), kvs::Storage< Record >::remove(), kvs::Trie::remove(), and kvs::Log::remove().
get()
std::optional< KeyValue > kvs::KeyValueStore::get (const Key & key) const
Получить пару KeyValue по ключу key.
Parameters
key Ключ.
Returns
KeyValue обернутый в std::optional, если в KeyValueStore есть Value по ключу key; пустой std::optional иначе.
References kvs::Storage< Record >::get(), kvs::Trie::get(), kvs::Log::get(), kvs::Record::getKey(), kvs::Record::getValue(), and kvs::BloomFilter::mightContains().
Referenced by main().
The documentation for this class was generated from the following files:
/github/workspace/include/KeyValueStore.hpp
KeyValueStore.cpp