KeyValueStorage: kvs::Record Class Reference
kvs::Record Class Reference
Class representing record KeyValue in the file : key, boolean flag, and value.
#include <Record.hpp>
Public Member Functions
Record (Key key, bool isOutdated, Value value)
const Key & getKey () const
bool getIsOutdated () const
const Value & getValue () const
Detailed Description
Class representing record KeyValue in the file : key, boolean flag, and value.
Constructor & Destructor Documentation
Record()
kvs::Record::Record (Key key, bool isOutdated, Value value)
Parameters
key Stored key.
isOutdated Whether this record is outdated.
value Stored value.
Member Function Documentation
getIsOutdated()
bool kvs::Record::getIsOutdated () const
Referenced by kvs::Storage< Record >::get(), kvs::Storage< Record >::rebuild(), and kvs::RecordSerializer::recordToBytes().
getKey()
const Key & kvs::Record::getKey () const
Referenced by kvs::KeyValueStore::get(), and kvs::RecordSerializer::recordToBytes().
getValue()
const Value & kvs::Record::getValue () const
Referenced by kvs::KeyValueStore::get(), and kvs::RecordSerializer::recordToBytes().
The documentation for this class was generated from the following files:
/github/workspace/include/model/Record.hpp
model/Record.cpp