KeyValueStorage: kvs::Storage< Record > Class Reference
kvs::Storage< Record > Class Reference
Класс для хранения Record на диске.
#include <Storage.hpp>
Classes
struct RecordStorageIterator
Public Member Functions
Storage (File &dataFile, const RecordSerializer &recordSerializer)
Id add (const Record &record)
std::optional< Record > get (const Id &id) const
std::optional< Record > getAnyway (const Id &id)
void remove (const Id &id)
void clear ()
bool isFull () const
void removeRecordsById (const std::vector< Id > &idsToRemove)
void rebuild ()
std::size_t size () const
Detailed Description
Класс для хранения Record на диске.
Constructor & Destructor Documentation
Storage()
kvs::Storage< Record >::Storage (File & dataFile, const RecordSerializer & recordSerializer) inline
Parameters
dataFile Файл для записи Record-ов.
recordSerializer Класс, сериализующий Record-ы.
Member Function Documentation
add()
Id kvs::Storage< Record >::add (const Record & record) inline
Добавить record в хранилище и присвоить ему идентификатор внутри хранилища.
Parameters
record Добавляемая запись.
Returns
Присвоенный идентификатор.
References kvs::FileOffset::getOffset().
Referenced by kvs::KeyValueStore::add().
clear()
void kvs::Storage< Record >::clear () inline
Очищает хранилище.
Referenced by kvs::KeyValueStore::clear().
get()
std::optional<Record> kvs::Storage< Record >::get (const Id & id) const inline
Получить Record по id.
Parameters
id Идентификатор объекта.
Returns
Record обернутый в std::optional, если в Storage есть какой-то объект с id; пустой std::optional иначе.
References kvs::Record::getIsOutdated().
Referenced by kvs::KeyValueStore::get().
getAnyway()
std::optional<Record> kvs::Storage< Record >::getAnyway (const Id & id) inline
Получить Record по id. Контракт : объект с таким id всегда существует, но возможно он устарел.
Parameters
id Идентификатор объекта.
Returns
Record обернутый в std::optional.
isFull()
bool kvs::Storage< Record >::isFull () const inline
Проверяет, заполнено ли хранилище.
Returns
true, если заполнено; false иначе.
Referenced by kvs::KeyValueStore::add(), and kvs::KeyValueStore::del().
rebuild()
void kvs::Storage< Record >::rebuild () inline
Перестраивает хранилище, удаляя устаревшие записи и оставляя остальные.
References kvs::Record::getIsOutdated().
remove()
void kvs::Storage< Record >::remove (const Id & id) inline
Удаляет объект с id. Если объекта нет, ничего не делает.
Parameters
id Идентификатор удаляемого объекта.
Referenced by kvs::KeyValueStore::add(), and kvs::KeyValueStore::del().
removeRecordsById()
void kvs::Storage< Record >::removeRecordsById (const std::vector< Id > & idsToRemove) inline
Удаляет из хранилища все записи с переданными Id
Parameters
idsToRemove Массив Id, по которым надо удалить записи.
References kvs::Storage< T >::remove().
Referenced by kvs::KeyValueStore::add().
size()
std::size_t kvs::Storage< Record >::size () const inline
Returns
Размер хранилища.
Referenced by kvs::KeyValueStore::clear().
The documentation for this class was generated from the following file:
/github/workspace/include/storage/Storage.hpp