KeyValueStorage: kvs::RecordSerializer Class Reference
kvs::RecordSerializer Class Reference
Class responsible for Record serialization and deserialization.
#include <RecordSerializer.hpp>
Public Member Functions
RecordSerializer (std::size_t key_size, std::size_t value_size)
char * recordToBytes (const Record &record) const
Record bytesToRecord (const char *bytes) const
std::size_t getKeySize () const
std::size_t getValueSize () const
Detailed Description
Class responsible for Record serialization and deserialization.
Constructor & Destructor Documentation
RecordSerializer()
kvs::RecordSerializer::RecordSerializer (std::size_t key_size, std::size_t value_size)
Parameters
key_size Key size (in bytes).
value_size Value size (in bytes).
Member Function Documentation
bytesToRecord()
Record kvs::RecordSerializer::bytesToRecord (const char * bytes) const
Transform byte sequence to Record.
Parameters
bytes Array of bytes representing Record.
Returns
The record.
getKeySize()
std::size_t kvs::RecordSerializer::getKeySize () const
getValueSize()
std::size_t kvs::RecordSerializer::getValueSize () const
recordToBytes()
char * kvs::RecordSerializer::recordToBytes (const Record & record) const
Transform Record in sequence of bytes.
Parameters
record Record to transform.
Returns
Array of bytes after serialization.
References kvs::Record::getIsOutdated(), kvs::Key::getKey(), kvs::Record::getKey(), kvs::Key::getSize(), kvs::Value::getSize(), kvs::Record::getValue(), and kvs::Value::getValue().
The documentation for this class was generated from the following files:
/github/workspace/include/serializer/RecordSerializer.hpp
serializer/RecordSerializer.cpp