KeyValueStorage: kvs::Log Class Reference
kvs::Log Class Reference
Class representing data storage in RAM, wrapping std::unordered_map and storing pairs < Key, Id>.
#include <Log.hpp>
Classes
struct LogIterator
Log iterator over _logMap.
Public Member Functions
Log (std::size_t sizeLimit)
std::optional< Id > add (const Key &key, const Id &id) override
std::optional< Id > remove (const Key &key) override
std::optional< Id > get (const Key &key) const override
void clear () override
bool isFull () const
std::shared_ptr< InMemoryTrieNode > toInMemoryTrieNode () const
Public Member Functions inherited from kvs::LogicStorage
virtual std::optional< Id > add (const Key &key, const Id &id)=0
virtual std::optional< Id > remove (const Key &key)=0
virtual std::optional< Id > get (const Key &key) const =0
virtual void clear ()=0
virtual ~LogicStorage ()=default
Detailed Description
Class representing data storage in RAM, wrapping std::unordered_map and storing pairs < Key, Id>.
Constructor & Destructor Documentation
Log()
kvs::Log::Log (std::size_t sizeLimit) explicit
Parameters
sizeLimit Maximal storage size.
Member Function Documentation
add()
std::optional< Id > kvs::Log::add (const Key & key, const Id & id) override virtual
Insert value id in Log by key. If there is an identifier by key, then Id will be updated.
Parameters
key Key.
id Identifier.
Returns
Id wrapped into std::optional, if there was some identifier by key in Log; empty std::optional otherwise.
Implements kvs::LogicStorage.
References get().
Referenced by kvs::KeyValueStore::add().
clear()
void kvs::Log::clear () override virtual
Clean up Log.
Implements kvs::LogicStorage.
Referenced by kvs::KeyValueStore::add(), and kvs::KeyValueStore::clear().
get()
std::optional< Id > kvs::Log::get (const Key & key) const override virtual
Get Id by key.
Parameters
key Key.
Returns
Id wrapped into std::optional, if there was some identifier by key in Log; empty std::optional otherwise.
Implements kvs::LogicStorage.
Referenced by add(), kvs::KeyValueStore::get(), and remove().
isFull()
bool kvs::Log::isFull () const
Check whether Log is full.
Returns
true if log is full; false otherwise.
Referenced by kvs::KeyValueStore::add().
remove()
std::optional< Id > kvs::Log::remove (const Key & key) override virtual
Remove key-value pair by key.
Parameters
key Key.
Returns
Id wrapped into std::optional, if there was some identifier by key in Log; empty std::optional otherwise.
Implements kvs::LogicStorage.
References get().
Referenced by kvs::KeyValueStore::del().
toInMemoryTrieNode()
std::shared_ptr< InMemoryTrieNode > kvs::Log::toInMemoryTrieNode () const
Turn Log-а into trie storing in RAM.
Returns
Pointer on the root of resulting trie.
References kvs::InMemoryTrieNode::add().
Referenced by kvs::KeyValueStore::add().
The documentation for this class was generated from the following files:
/github/workspace/include/storage/Log.hpp
storage/Log.cpp