KeyValueStorage: kvs::FileOffset Class Reference
kvs::FileOffset Class Reference
Класс, представляющий позицию в файле.
#include <FileOffset.hpp>
Public Member Functions
FileOffset (size_t offset)
off64_t getOffset () const
Detailed Description
Класс, представляющий позицию в файле.
Constructor & Destructor Documentation
FileOffset()
kvs::FileOffset::FileOffset (size_t offset) explicit
Parameters
offset Хранимая позиция.
Member Function Documentation
getOffset()
off64_t kvs::FileOffset::getOffset () const
Returns
Хранимая позиция.
Referenced by kvs::Storage< Record >::add(), kvs::Storage< TrieNode >::add(), kvs::Storage< TrieNode >::addTrieNodeSubtree(), kvs::File::read(), and kvs::File::writeByOffset().
The documentation for this class was generated from the following files:
/github/workspace/include/model/FileOffset.hpp
model/FileOffset.cpp