KeyValueStorage: kvs::BloomFilter Class Reference
kvs::BloomFilter Class Reference
Класс, реализующий фильтр Блума.
#include <BloomFilter.hpp>
Public Member Functions
BloomFilter (std::size_t size)
void add (const Key &key)
bool mightContains (const Key &key) const
Detailed Description
Класс, реализующий фильтр Блума.
Constructor & Destructor Documentation
BloomFilter()
kvs::BloomFilter::BloomFilter (std::size_t size) explicit
Parameters
size Размер фильтр блума.
Member Function Documentation
add()
void kvs::BloomFilter::add (const Key & key)
Parameters
key Ключ, добавляемый в фильтр.
References kvs::Key::getKey(), and kvs::Key::getSize().
Referenced by kvs::KeyValueStore::add().
mightContains()
bool kvs::BloomFilter::mightContains (const Key & key) const
Parameters
key Ключ, наличие которого в фильтр проверяем.
Returns
true, если ключ может содержаться в фильтре; false, если ключа точно нет в фильтре.
References kvs::Key::getKey(), and kvs::Key::getSize().
Referenced by kvs::KeyValueStore::del(), and kvs::KeyValueStore::get().
The documentation for this class was generated from the following files:
/github/workspace/include/storage/BloomFilter.hpp
storage/BloomFilter.cpp