KeyValueStorage: kvs::InMemoryTrieNode Class Reference
kvs::InMemoryTrieNode Class Reference
A class implementing a trie node in RAM.
#include <InMemoryTrieNode.hpp>
Public Member Functions
InMemoryTrieNode ()
std::shared_ptr< InMemoryTrieNode > get (std::size_t index) const
Id getId () const
Static Public Member Functions
static void add (std::shared_ptr< InMemoryTrieNode > currentNode, const Key &key, const Id &id)
static std::shared_ptr< InMemoryTrieNode > toInMemoryTrieNode (std::vector< std::pair< Key, Id > > &keyIdPairs)
Detailed Description
A class implementing a trie node in RAM.
Constructor & Destructor Documentation
InMemoryTrieNode()
kvs::InMemoryTrieNode::InMemoryTrieNode ()
Initialize children with nullptr.
Referenced by add(), and toInMemoryTrieNode().
Member Function Documentation
add()
void kvs::InMemoryTrieNode::add (std::shared_ptr< InMemoryTrieNode > currentNode, const Key & key, const Id & id) static
Parameters
currentNode Node to which key with id is attached as a root.
key The key we want to add to the tree currentNode.
id Identifier of the record corresponding to the key.
References kvs::Key::getKey(), kvs::Key::getSize(), and InMemoryTrieNode().
Referenced by kvs::Log::toInMemoryTrieNode(), and toInMemoryTrieNode().
get()
std::shared_ptr< InMemoryTrieNode > kvs::InMemoryTrieNode::get (std::size_t index) const
Parameters
index Node's child number.
Returns
Pointer to the index of the child.
getId()
Id kvs::InMemoryTrieNode::getId () const
Returns
Identifier of the corresponding node record. If the node does not match the record, then std::numeric_limits<std::size_t>::max().
toInMemoryTrieNode()
std::shared_ptr< InMemoryTrieNode > kvs::InMemoryTrieNode::toInMemoryTrieNode (std::vector< std::pair< Key, Id > > & keyIdPairs) static
Turning Log-a into a Trie stored in RAM.
Parameters
keyIdPairs Array of pairs < Key, Id - identifier of Record>, from which the trie will be built.
Returns
Pointer to the root of the resulting trie.
References add(), and InMemoryTrieNode().
The documentation for this class was generated from the following files:
/github/workspace/include/model/InMemoryTrieNode.hpp
model/InMemoryTrieNode.cpp