KeyValueStorage: kvs::Key Class Reference
kvs::Key Class Reference
Class representing key and its size.
#include <Key.hpp>
Public Member Functions
Key (const char *key, size_t size)
Key (const Key &key)
Key & operator= (const Key &key)
Key (Key &&key) noexcept
Key & operator= (Key &&key) noexcept
~Key ()
const char * getKey () const
size_t getSize () const
bool operator== (const Key &key) const
Detailed Description
Class representing key and its size.
Constructor & Destructor Documentation
Key() [1/3]
kvs::Key::Key (const char * key, size_t size)
Key() [2/3]
kvs::Key::Key (const Key & key)
Key() [3/3]
kvs::Key::Key (Key && key) noexcept
~Key()
kvs::Key::~Key ()
Member Function Documentation
getKey()
const char * kvs::Key::getKey () const
Referenced by kvs::BloomFilter::add(), kvs::InMemoryTrieNode::add(), kvs::BloomFilter::mightContains(), operator==(), and kvs::RecordSerializer::recordToBytes().
getSize()
size_t kvs::Key::getSize () const
Referenced by kvs::BloomFilter::add(), kvs::InMemoryTrieNode::add(), kvs::BloomFilter::mightContains(), and kvs::RecordSerializer::recordToBytes().
operator=() [1/2]
Key & kvs::Key::operator= (const Key & key)
operator=() [2/2]
Key & kvs::Key::operator= (Key && key) noexcept
operator==()
bool kvs::Key::operator== (const Key & key) const
References getKey().
The documentation for this class was generated from the following files:
/github/workspace/include/model/Key.hpp
model/Key.cpp