KeyValueStorage: kvs::Trie Class Reference
kvs::Trie Class Reference
Class representing trie storage on the disk, which stored pairs < Key, Id>.
#include <Trie.hpp>
Public Member Functions
Trie (Storage< TrieNode > &_storage)
std::optional< Id > add (const Key &, const Id &) override
std::optional< Id > remove (const Key &) override
std::optional< Id > get (const Key &) const override
void clear () override
const std::vector< Id > & merge (const std::shared_ptr< InMemoryTrieNode > &smallTrieRoot)
Public Member Functions inherited from kvs::LogicStorage
virtual std::optional< Id > add (const Key &key, const Id &id)=0
virtual std::optional< Id > remove (const Key &key)=0
virtual std::optional< Id > get (const Key &key) const =0
virtual void clear ()=0
virtual ~LogicStorage ()=default
Detailed Description
Class representing trie storage on the disk, which stored pairs < Key, Id>.
Constructor & Destructor Documentation
Trie()
kvs::Trie::Trie (Storage< TrieNode > & _storage) explicit
Parameters
_storage Storage TrieNode of trie nodes, responsible only for access to nodes.
Member Function Documentation
add()
std::optional< Id > kvs::Trie::add (const Key & key, const Id & recordId) override virtual
Insert value id in Trie by key. If there was some identifier in Trie by key, then Id will be updated
Parameters
key Key.
id Identifier.
Returns
Id wrapped into std::optional, if there was some identifier in Trie by key; empty std::optional otherwise.
Implements kvs::LogicStorage.
References kvs::Storage< TrieNode >::replace().
clear()
void kvs::Trie::clear () override virtual
Clean up Trie.
Implements kvs::LogicStorage.
References kvs::Storage< TrieNode >::clear().
Referenced by kvs::KeyValueStore::clear().
get()
std::optional< Id > kvs::Trie::get (const Key & key) const override virtual
Get Id by key.
Parameters
key Key.
Returns
Id wrapped into std::optional, if there was some identifier in Trie by key; empty std::optional otherwise.
Implements kvs::LogicStorage.
Referenced by kvs::KeyValueStore::get().
merge()
const std::vector< Id > & kvs::Trie::merge (const std::shared_ptr< InMemoryTrieNode > & smallTrieRoot)
Merge the RAM trie with the root smallTrieRoot in current trie.
Parameters
smallTrieRoot Root of the RAM trie.
Returns
Array of outdated Id after merge.
References merge().
Referenced by kvs::KeyValueStore::add(), and merge().
remove()
std::optional< Id > kvs::Trie::remove (const Key & key) override virtual
Remove key-value pair with key.
Parameters
key Key.
Returns
Id wrapped into std::optional, if there was some identifier in Trie by key; empty std::optional otherwise.
Implements kvs::LogicStorage.
References kvs::Storage< TrieNode >::replace().
Referenced by kvs::KeyValueStore::del().
The documentation for this class was generated from the following files:
/github/workspace/include/storage/Trie.hpp
storage/Trie.cpp