KeyValueStorage: kvs::TrieNodeSerializer Class Reference
kvs::TrieNodeSerializer Class Reference
Class responsible for TrieNode serialization and deserialization.
#include <TrieNodeSerializer.hpp>
Public Member Functions
TrieNodeSerializer (std::size_t idSize)
char * trieNodeToBytes (const TrieNode &trieNode) const
TrieNode bytesToTrieNode (const char *bytes) const
Detailed Description
Class responsible for TrieNode serialization and deserialization.
Constructor & Destructor Documentation
TrieNodeSerializer()
kvs::TrieNodeSerializer::TrieNodeSerializer (std::size_t idSize) explicit
Parameters
idSize Size of Id (in bytes).
Member Function Documentation
bytesToTrieNode()
TrieNode kvs::TrieNodeSerializer::bytesToTrieNode (const char * bytes) const
Transform byte sequence to TrieNode.
Parameters
bytes Array of bytes representing TrieNode.
Returns
The record.
References kvs::Id::getIdSize().
trieNodeToBytes()
char * kvs::TrieNodeSerializer::trieNodeToBytes (const TrieNode & trieNode) const
Transform TrieNode in sequence of bytes.
Parameters
trieNode Transformable node.
Returns
Array of bytes after transforming.
References kvs::Id::getIdSize(), and kvs::TrieNode::getNextRecords().
The documentation for this class was generated from the following files:
/github/workspace/include/serializer/TrieNodeSerializer.hpp
serializer/TrieNodeSerializer.cpp