KeyValueStorage: kvs::Storage< TrieNode > Class Reference
kvs::Storage< TrieNode > Class Reference
Class storing Record on the disk.
#include <Storage.hpp>
Public Member Functions
Storage (File &trieNodeFile, const TrieNodeSerializer &trieNodeSerializer)
Id add (const TrieNode &trieNode)
std::optional< TrieNode > get (const Id &id) const
void remove (const Id &id)=delete
void replace (const Id &id, const TrieNode &trieNode)
void clear ()
Id addTrieNodeSubtree (const std::shared_ptr< InMemoryTrieNode > &node)
Detailed Description
Class storing Record on the disk.
Constructor & Destructor Documentation
Storage()
kvs::Storage< TrieNode >::Storage (File & trieNodeFile, const TrieNodeSerializer & trieNodeSerializer) inline
Parameters
trieNodeFile File to writing TrieNode.
trieNodeSerializer Class serializing TrieNode.
Member Function Documentation
add()
Id kvs::Storage< TrieNode >::add (const TrieNode & trieNode) inline
Add record in storage and assign it identifier.
Parameters
trieNode Inserted trie node.
Returns
Assigned identifier.
References kvs::FileOffset::getOffset().
addTrieNodeSubtree()
Id kvs::Storage< TrieNode >::addTrieNodeSubtree (const std::shared_ptr< InMemoryTrieNode > & node) inline
Add all nodes of the given trie to storage.
Parameters
node Root of the given trie.
Returns
Root identifier of the node in storage.
References kvs::Storage< T >::add(), and kvs::FileOffset::getOffset().
clear()
void kvs::Storage< TrieNode >::clear () inline
Clean up storage.
Referenced by kvs::Trie::clear().
get()
std::optional< TrieNode > kvs::Storage< TrieNode >::get (const Id & id) const inline
Get TrieNode by id. Contract : there is TrieNode by id.
Parameters
id Object identifier.
Returns
TrieNode wrapped into std::optional.
remove()
void kvs::Storage< TrieNode >::remove (const Id & id) delete
replace()
void kvs::Storage< TrieNode >::replace (const Id & id, const TrieNode & trieNode) inline
Write by id a new trieNode.
Parameters
id Identifier.
trieNode TrieNode.
Referenced by kvs::Trie::add(), and kvs::Trie::remove().
The documentation for this class was generated from the following file:
/github/workspace/include/storage/Storage.hpp